### ISSUE TITLE
Support jQuery 3.1

### ISSUE THREAD

**Issue by 3noch** [indrimuska/jquery-editable-select#12]

**Comment by indrimuska** [comment]
Hi @3noch, in [this fiddle](https://jsfiddle.net/8vw34tuz/1/) I've used jQuery 2.2.4 and everything seems to work fine. Otherwise, it doesn't work with jQuery ≥3 yet, but it will (I'm going to release new versions the next days). If you need it now, just replace all `.size()` methods with `.length`.
Thank you for reporting this. 👍

**Comment by 3noch** [comment]
Cool. If it works with 2.2 will you update `package.json` to allow it?

**Comment by indrimuska** [comment]
Sure, I'll do it right now!

**Comment by 3noch** [comment]
Might want to update `bower.json` too. Thanks for updating this.

**Comment by indrimuska** [comment]
Done, check them out! ;)

**Comment by 3noch** [comment]
@indrimuska Thank you! Looks like bower won't pick up these changes until you make a new release though.

**Comment by indrimuska** [comment]
Yes, I know, the same is for NPM. Please, wait tomorrow for a new release.

**Comment by 3noch** [comment]
No problem. I'll use a git clone for now. Thanks very much.

**Comment by indrimuska** [comment]
Full support for jQuery 3.1 is now available in the latest release [2.0.1](https://github.com/indrimuska/jquery-editable-select/releases/tag/2.0.1).

**Comment by 3noch** [comment]
Thanks @indrimuska!
